name: CI_CD
on: [push,pull_request]
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install dependences
        run: npm install
      - name: Run tests
        run: npm test
     